// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edit_userinfo.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editUserInfo = `-- name: EditUserInfo :one
UPDATE users
SET email = $1, hashed_password = $2 
WHERE id = $3
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type EditUserInfoParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) EditUserInfo(ctx context.Context, arg EditUserInfoParams) (User, error) {
	row := q.db.QueryRowContext(ctx, editUserInfo, arg.Email, arg.HashedPassword, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
